FROM python:3.10-slim

WORKDIR /app

COPY . /app

# Instala gcc e python3-dev para compilar pacotes nativos
RUN apt-get update && apt-get install -y gcc python3-dev && rm -rf /var/lib/apt/lists/*

RUN pip install -r requirements.txt

RUN chmod +x entrypoint.sh
CMD ["./entrypoint.sh"]
